---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  daemon.json: |
    {
      "insecure-registries" : ["192.168.0.149:5000"]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: docker-in-docker
  namespace: kube-system
  labels:
    app: docker-in-docker
spec:
  type: NodePort
  ports:
  - name: dind
    port: 2375
    targetPort: 2375
    nodePort: 2375
  selector:
    app: docker-in-docker
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: docker-in-docker
  namespace: kube-system
  labels:
    app: docker-in-docker
spec:
  serviceName: docker-in-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-in-docker
    spec:
      containers:
        - name: docker-in-docker
          image: docker:dind
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
          - containerPort: 2375
            name: dind
          volumeMounts:
            - name: config-volume
              mountPath: /etc/docker
            - name: docker-image-storage
              mountPath: /var/lib/docker
      volumes:
        - name: config-volume
          configMap:
            name: dind-config
        - name: docker-image-storage
          persistentVolumeClaim:
            claimName: dind-data
---

