---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: docker-in-docker
  namespace: kube-system
  labels:
    app: docker-in-docker
spec:
  type: NodePort
  ports:
  - name: dind
    port: 2375
    targetPort: 2375
    nodePort: 2375
  selector:
    app: docker-in-docker
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: docker-in-docker
  namespace: kube-system
  labels:
    app: docker-in-docker
spec:
  serviceName: docker-in-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-in-docker
    spec:
      containers:
      - name: docker-in-docker
        image: docker:dind
        args:
        - dockerd
        - --storage-driver=overlay2
        - -H unix:///var/run/dind/docker.sock -H tcp://0.0.0.0:2375
        securityContext:
          privileged: true
        ports:
        - containerPort: 2375
          name: dind
        volumeMounts:
        - name: rundind
          mountPath: /var/run/dind
        - name: docker-image-storage
          mountPath: /var/lib/docker
      terminationGracePeriodSeconds: 30
      volumes:
        - name: docker-image-storage
          persistentVolumeClaim:
            claimName: dind-data
        - name: rundind
          hostPath:
            path: /var/run/dind/
---

