---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dind-service
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    name:  dind
  type: "ClusterIP"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dind
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name:  dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --storage-driver=overlay2
          - -H unix:///var/run/dind/docker.sock
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-image-storage
          mountPath: /var/lib/docker
        - name: rundind
          mountPath: /var/run/dind
      terminationGracePeriodSeconds: 30
      volumes:
      - name: docker-image-storage
        persistentVolumeClaim:
          claimName: dind-data
      - name: rundind
        hostPath:
          path: /var/run/dind/