apiVersion: v1
kind: Service
metadata:
  name: dind-service
  namespace: kube-system
spec:
  ports:
    - name: dind
      port: 2375
      protocol: TCP
      targetPort: 2375
      nodePort: 32375
  selector:
    name:  dind
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dind
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --storage-driver=overlay2
          - -H fd:// -H tcp://0.0.0.0:2376
        securityContext:
          privileged: true
        ports:
          - containerPort: 2375
            name: dind
        volumeMounts:
        - name: varlibdocker
          mountPath: /var/lib/docker
        - name: rundind
          mountPath: /var/run/dind
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlibdocker
        emptyDir: {}
      - name: rundind
        hostPath:
          path: /var/run/dind/