---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  daemon.json: |
    {
      "hosts": ["tcp://0.0.0.0:2376","unix:///var/run/docker.sock"]
      "insecure-registries" : ["harbor.seos.segma.tech"]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: dind-service
  namespace: kube-system
spec:
  ports:
    - name: dind
      port: 2375
      protocol: TCP
      targetPort: 2375
      nodePort: 32375
  selector:
    name:  dind
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dind
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --storage-driver=overlay2
        securityContext:
          privileged: true
        ports:
          - containerPort: 2375
            name: dind
        volumeMounts:
        - name: varlibdocker
          mountPath: /var/lib/docker
        - name: rundind
          mountPath: /var/run/dind
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlibdocker
        emptyDir: {}
      - name: rundind
        hostPath:
          path: /var/run/dind/
