---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  daemon.json: |
    {
      "insecure-registries" : ["harbor.seos.segma.tech"]
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dind-service
  namespace: kube-system
spec:
  ports:
    - name: dind
      port: 2376
      protocol: TCP
      targetPort: 2376
      nodePort: 32376
  selector:
    name:  dind
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dind
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --storage-driver=overlay2
          - -H tcp://0.0.0.0:2376
          - -H unix:///var/run/docker.sock
        securityContext:
          privileged: true
        ports:
          - containerPort: 2376
            name: dind
        volumeMounts:
        - name: varlibdocker
          mountPath: /var/lib/docker
        - name: rundind
          mountPath: /var/run/dind
        - name: config-volume
          mountPath: /etc/docker
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: dind-config
      - name: varlibdocker
        persistentVolumeClaim:
          claimName: dind-data
      - name: rundind
        hostPath:
          path: /var/run/dind/
