# 使用之前需要先创建docker config 的 secret。同步本地docker配置
# kubectl create secret generic docker-cfg --from-file="/root/config.json"  --namespace=engine
---
apiVersion: v1
kind: Service
metadata:
  name: dind-service
spec:
  ports:
    - name: dind
      port: 2376
      protocol: TCP
      targetPort: 2376
      nodePort: 32376
  selector:
    name:  dind
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - -H tcp://0.0.0.0:2376
          - --insecure-registry=harbor.seos.segma.tech
        securityContext:
          privileged: true
        ports:
          - containerPort: 2376
            name: dind
        volumeMounts:
        - name: varlibdocker
          mountPath: /var/lib/docker
        - name: dindconfig
          mountPath: /root/.docker/config.json
          readOnly: true
        - name: rundind
          mountPath: /var/run/docker.sock
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlibdocker
        emptyDir: {}
      - name: dindconfig
        secret:
          secretName: docker-cfg
      - name: rundind
        hostPath:
          path: /var/run/docker.sock
