---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
      - namespaces
      - nodes
      - services
      - pods
      - pods/exec
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: gitlab-ce
